server:
  port: 8066

spring:
  application:
    name: cloudcase-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router
          lower-case-service-id: true  # 服务名小写
      # 路由(如果使用动态路由方式，不要在配置文件中配置路由）

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.135.128:3306/hlhk?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait-millis: 60000
  redis:
    host: 192.168.135.128
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com:
      mapper: debug
